IMAGE_WIDTH = 256
IMAGE_HEIGHT = 256
IMAGE_SIZE = (IMAGE_WIDTH, IMAGE_HEIGHT)

NUM_CLASSES = 1

BATCH_SIZE = 8
LEARNING_RATE = 0.0001
EPOCHS = 50

CNN_MODEL_NAME = "custom_cnn"
CONVNEXT_MODEL_NAME = "convnext_detector"

TRAIN_IMAGE_PATH = r"D:\DFUC_Project\Dataset\DFUC2020\DFUC_Training_Set\images"
